name: NCDS - Production CD

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: "Deployment"
        required: true
        type: choice
        options:
          - ncds

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: ncds-server
  CONTAINER_NAME: ncds-server
  ENV_FILE_PATH: ~/ncds-prod/.env
  LOGS_FOLDER: /home/ec2-user/ncds-prod/logs:/app/logs
  FIREBASE_TOKEN: /home/ec2-user/ncds-prod/pro910-ncds-firebase-adminsdk-fbsvc-617ec747ac.json:/app/pro910-ncds-firebase-adminsdk-fbsvc-617ec747ac.json
  BACKUPS_FOLDER: /home/ec2-user/ncds-prod/backups:/app/backups
  MONGO_DUMP: /home/ec2-user/ncds-prod/mongodump:/app/mongodump
  EXPOSED_PORTS: 8002:8002

jobs:
  run:
    runs-on: [self-hosted, Linux, X64] 
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640928555103:role/github-ci-cd
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "false"

      - name: Pull Docker image
        run: docker pull 640928555103.dkr.ecr.ap-south-1.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

      - name: Delete old docker container
        run: docker rm -f ${{ env.CONTAINER_NAME }} || true

      - name: Run docker container
        run: |
          docker run -d -p ${{ env.EXPOSED_PORTS }} \
            -v ${{ env.FIREBASE_TOKEN }} \
            -v ${{ env.LOGS_FOLDER }} \
            -v ${{ env.BACKUPS_FOLDER }} \
            -v ${{ env.MONGO_DUMP }} \
            --name ${{ env.CONTAINER_NAME }} \
            --env-file ${{ env.ENV_FILE_PATH }} \
            --restart always \
            640928555103.dkr.ecr.ap-south-1.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest